name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PRISMA_SKIP_POSTINSTALL: true
      NPM_CONFIG_FETCH_RETRIES: 5
      NPM_CONFIG_FETCH_RETRY_MINTIMEOUT: 20000
      NPM_CONFIG_FETCH_RETRY_MAXTIMEOUT: 120000
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Show environment versions
        run: |
          node -v
          npm -v

      - name: Install dependencies
        run: |
          npm install --no-audit --no-fund --no-optional

      - name: Lint
        run: |
          npm run -s lint || true

      - name: Build
        run: |
          npm run -s build


